workspace: '<your_workspace>'
experiments_dir: '${workspace}/runs/'
experiment_name: '${now:%Y-%m-%d-%H-%M-%S}'
device: 'cuda:0'
seed: 0



defaults:
  - _self_
  - model: Llama-3.1-8B-Instruct
  - dataset: Susy
  - evaluation: eval
  - logger: wandb
  